### ------------------- ⭐BOOKMARK API⭐ ---------------------- ###

### BOOMARK SELECT
GET  http://localhost:8000/api/bookmarks?user_id=59&place_id=712 HTTP/1.1
### BOOMARK CLICK (INSERT)
POST http://localhost:8000/api/bookmarks HTTP/1.1
Content-Type: application/json

{
    "user_id":59,
    "place_id":7
}
 112.187.123.29
### BOOMARK UNCLICK (DELETE)
DELETE http://localhost:8000/api/bookmarks?user_id=59&place_id=2 HTTP/1.1
Content-Type: application/json

