### ------------------- place API ---------------------- ###
### index
 HTTP/1.1

 

 

GET http://localhost:8000/api/places?place_code=1&lat=35.1449589&lon=126.9216603&pageNumber=0&user_id=59 HTTP/1.1

### SEARCH PAGE
  ##type = all 
GET http://localhost:8000/api/places/search?type=all&place_code=1   

### SEARCH PAGE
  ##type = filter 
GET http://localhost:8000/api/places/search?type=filter&menu=0&bed=0&tableware=0&meetingroom=0&diapers=0&playroom=0&carriage=0&nursingroom=0&chair=1