### 레스토랑
POST http://localhost:8000/api/prev-data/restaurants

### 병원
POST http://localhost:8000/api/prev-data/hospitals

### 어린이집
POST http://localhost:8000/api/prev-data/day-care-centers

### 키드 카페
POST http://localhost:8000/api/prev-data/kid-cafes

### 체험관
POST http://localhost:8000/api/prev-data/experience-centers