### ------------------- place API ---------------------- ###
### index
GET http://localhost:8000/api/places/test?place_code=1 HTTP/1.1

### LIST PAGE
 

GET http://localhost:8000/api/places?place_code=1&lat=35.1449589&lon=126.9216603&pageNumber=0&user_id=59 HTTP/1.1

