### ------------------- USER API ---------------------- ###

### find all user
GET http://localhost:8000/api/users HTTP/1.1

### find one user  
GET http://localhost:8000/api/users/73 HTTP/1.1

### get user nickname
GET http://localhost:8000/api/users/nickname?userId=2 HTTP/1.1 

### create user
POST http://localhost:8000/api/users HTTP/1.1
Content-Type: application/json

{
    "email":"test1234543@gmail.com",
    "nickname":null,
    "gender":"",
    "birthday":"",
    "age":"",
    "url":""
}

### update user 
# PUT http://localhost:8000/api/users/gojaebeom HTTP/1.1
# Content-Type: application/json

# {
#     "userId": 1,
#     "gender":"F",
#     "birthday":"2020-01-01",
#     "age":27
# }

PUT http://localhost:8000/api/users/54 HTTP/1.1
Content-Type: application/json

{
    "nickname": "akrom",
    "gender":"F",
    "birthday":"2020-01-01",
    "age":28
}
### find by options user data exam1 : 조건 없이 모든 유저를 조회
GET http://localhost:8000/api/users/find-by-options?select=* HTTP/1.1

### find by options user data exam2 : 조건 없이 1명 이상의 유저가 존재하는지 조회
GET http://localhost:8000/api/users/find-by-options?select=*&selectType=boolean HTTP/1.1

### find by options user data exam3 : 이메일 값을 통해 모든 데이터 조회
GET http://localhost:8000/api/users/find-by-options?select=*&whereColumn=email&whereData=akobidov777@gmail.comkakao 

### find by options user data exam4 : 닉네임 값을 통해 모든 데이터 조회
GET http://localhost:8000/api/users/find-by-options?select=*&whereColumn=nickname&whereData=미현 HTTP/1.1

### find by options user data exam5 : 닉네임 값을 통해 해당하는 닉네임이 있는지 참, 거짓으로 조회
GET http://localhost:8000/api/users/find-by-options?select=*&selectType=boolean&whereColumn=nickname&whereData=al HTTP/1.1

### find by options user data exam6 : id 값을 통해 닉네임, 이메일만 조회
GET http://localhost:8000/api/users/find-by-options?select=nickname,email&whereColumn=id&whereData=1 HTTP/1.1

### update by options exam1 : 유저의 프로필 url 수정
PATCH http://localhost:8000/api/users/1 HTTP/1.1
Content-Type: application/json

{
    "profile_image":"test2.jpg"
}

### update by options exam2 : 유저의 닉네임 수정
PATCH http://localhost:8000/api/users/1 HTTP/1.1
Content-Type: application/json

{
    "nickname":"jaebeom go"
}

### update by options exam3 : 유저의 특정 정보들 업데이트
PATCH http://localhost:8000/api/users/1 HTTP/1.1
Content-Type: application/json

{
    "nickname":"gojaebeom",
    "baby_birthday":"123456"
}

### update by options exam4 : id, email 등의 변경되면 안되는 값에 접근 시
PATCH http://localhost:8000/api/users/60 HTTP/1.1
Content-Type: application/json

{
    "profile_image":null
}

### delete : 유저 삭제
DELETE http://localhost:8000/api/users/1 HTTP/1.1
Content-Type: application/json








### FIND BY OPTION EAMIL
GET http://localhost:8000/api/users/find-by-option?option=email&optionData='1@gmail.comkakoao'

### FIND BY OPTION NICKNAME
GET http://localhost:8000/api/users/find-by-option?option=nickname&optionData='assassooa'

### FIND USERS
GET http://localhost:8000/api/users/77


